# Generated by Django 4.2.6 on 2023-11-04 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('genre', models.CharField(blank=True, choices=[('Fiction', 'Fiction'), ('Narrative', 'Narrative'), ('Novel', 'Novel'), ('Mystery', 'Mystery')], max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
